# Generated by Django 5.2.3 on 2025-06-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
