# Generated by Django 5.2.3 on 2025-06-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='full_name',
            new_name='name',
        ),
    ]
