# Generated by Django 5.2.3 on 2025-07-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_currency_transaction_from_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cashier',
            new_name='agent',
        ),
    ]
